fs: proc: task_mmu: remove unused variable
/home/skye/not/fs/proc/task_mmu.c:1010:25: error: unused variable 'pad_vma' [-Werror,-Wunused-variable]
 1010 |         struct vm_area_struct *pad_vma = get_pad_vma(v);

It's caller was removed in commit 566023839509